- name: Get additionnal metrics ports names
  ansible.builtin.set_fact:
    additionnal_metrics_port_name: "{{ gitlab_pods.resources
      | selectattr('metadata.name', 'contains', item.name)
      | map(attribute='spec.containers') | first
      | selectattr('name', 'contains', item.name)
      | map(attribute='ports') | first
      | selectattr('containerPort', 'equalto', item.port)
      | map(attribute='name') | first }}"

- name: Declare PodMonitors
  kubernetes.core.k8s:
    template: podmonitor.yml.j2
