---
- name: Get metrics endpoint port name
  ansible.builtin.set_fact:
    metrics_port_name: "{{ endpoints.resources
      | selectattr('metadata.name', 'contains', item.name)
      | selectattr('metadata.name', 'contains', item.metrics_endpoint_name | default(item.name))
      | map(attribute='subsets') | first
      | map(attribute='ports') | first
      | selectattr('port', 'equalto', item.port)
      | map(attribute='name') | first }}"

- name: Get Service Monitor name
  ansible.builtin.set_fact:
    service_monitor: "{{ service_monitors.resources
      | selectattr('metadata.name', 'contains', item.name)
      | map(attribute='metadata.name') | first }}"

- name: Patch ServiceMonitor
  kubernetes.core.k8s:
    api_version: monitoring.coreos.com/v1
    kind: ServiceMonitor
    namespace: "{{ dsc.gitlab.namespace }}"
    name: "{{ service_monitor }}"
    state: patched
    definition:
      spec:
        endpoints:
          - bearerTokenSecret:
              key: ""
            interval: 30s
            path: "{{item.path}}"
            port: "{{ metrics_port_name }}"
