---
- name: Create Sonarqube namespace
  kubernetes.core.k8s:
    kind: Namespace
    name: "{{ dsc.sonarqube.namespace }}"

- name: Create PostgreSQL cluster and sonar database
  kubernetes.core.k8s:
    template: pg-cluster-sonar.yaml.j2

- name: Wait pg-cluster-sonar-rw endpoint
  kubernetes.core.k8s_info:
    kind: Endpoints
    namespace: "{{ dsc.sonarqube.namespace }}"
    name: pg-cluster-sonar-rw
  register: endpoint
  until: endpoint.resources[0].subsets[0].addresses[0] is defined
  retries: 30
  delay: 5

- name: Wait job.batch/pg-cluster-sonar-1-initdb to be terminated
  kubernetes.core.k8s_info:
    kind: Job
    api_version: batch/v1
    namespace: "{{ dsc.sonarqube.namespace }}"
    name: pg-cluster-sonar-1-initdb
  register: job1
  until: job1.resources | length == 0
  retries: 30
  delay: 5

- name: Add SonarQube helm repo
  kubernetes.core.helm_repository:
    name: sonarqube
    repo_url: https://SonarSource.github.io/helm-chart-sonarqube

- name: Get admin password secret
  kubernetes.core.k8s_info:
    kind: Secret
    namespace: "{{ dsc.sonarqube.namespace }}"
    name: sonarqube
  register: admin_password_secret

- name: Set admin password secret
  when: admin_password_secret.resources | length == 0
  no_log: true
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      data:
        password: "{{ lookup('password', '/dev/null length=24 chars=ascii_letters,digits') | b64encode }}"
        currentPassword: "{{ 'admin' | b64encode }}"
      metadata:
        name: sonarqube
        namespace: "{{ dsc.sonarqube.namespace }}"
      type: Opaque

- name: Get SonarQube monitoring password secret
  no_log: true
  kubernetes.core.k8s_info:
    namespace: "{{ dsc.sonarqube.namespace }}"
    kind: Secret
    name: sonar-monitoring-password
  register: sonar_monitoring_secret

- name: Set SonarQube monitoring password secret
  when: sonar_monitoring_secret.resources | length == 0
  no_log: true
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      data:
        monitoring-password: "{{ lookup('password', '/dev/null length=24 chars=ascii_letters,digits') | b64encode }}"
      metadata:
        name: sonar-monitoring-password
        namespace: "{{ dsc.sonarqube.namespace }}"
      type: Opaque

- name: Get Sonar client secret
  kubernetes.core.k8s_info:
    kind: Secret
    namespace: "{{ dsc.keycloak.namespace }}"
    name: keycloak-client-secret-sonar-client
  register: sonar_secret
  failed_when: sonar_secret.resources | length == 0

- name: Set settings fact
  ansible.builtin.set_fact:
    keycloak_secret: "{{ sonar_secret.resources[0].data.CLIENT_SECRET | b64decode }}"
    keycloak_client: "{{ sonar_secret.resources[0].data.CLIENT_ID | b64decode }}"

- name: Set path fact
  ansible.builtin.set_fact:
    path: "{{ role_path + '/templates/values' }}"

- name: Compute Sonarqube Helm values
  ansible.builtin.include_role:
    name: combine
  vars:
    combine_path: "{{ path }}"
    combine_user_values: "{{ dsc.sonarqube['values'] }}"
    combine_dest_var: "sonar_values"

- name: Deploy helm
  kubernetes.core.helm:
    name: sonarqube
    chart_ref: sonarqube/sonarqube
    chart_version: "{{ dsc.sonarqube.chartVersion }}"
    release_namespace: "{{ dsc.sonarqube.namespace }}"
    create_namespace: true
    values: "{{ sonar_values }}"

- name: Wait sonarqube endpoint to initialize
  kubernetes.core.k8s_info:
    kind: Endpoints
    namespace: "{{ dsc.sonarqube.namespace }}"
    name: sonarqube-sonarqube
  register: endpoint
  until: endpoint.resources[0].subsets[0].addresses[0].ip is defined
  retries: 45
  delay: 5

- name: Get DSO Console inventory
  kubernetes.core.k8s_info:
    namespace: "{{ dsc.console.namespace }}"
    kind: ConfigMap
    name: dso-config
  register: ansible_inventory

- name: Get SonarQube version
  ansible.builtin.uri:
    url: https://{{ sonar_domain }}/api/server/version
    method: GET
    return_content: true
  register: sonar_version

- name: Reset Admin Password procedure
  when: ansible_inventory.resources[0].data.SONAR_API_TOKEN is undefined
  ansible.builtin.include_tasks:
    file: reset-admin-password.yaml

- name: Set fact sonar token
  when: ansible_inventory.resources[0].data.SONAR_API_TOKEN is defined
  ansible.builtin.set_fact:
    token_pass: "{{ ansible_inventory.resources[0].data.SONAR_API_TOKEN }}"
  no_log: true

- name: Remove permissions for sonar-users
  ansible.builtin.uri:
    url: https://{{ sonar_domain }}/api/permissions/remove_group?groupName=sonar-users&permission={{ item }}
    user: "{{ token_pass }}"
    force_basic_auth: true
    validate_certs: "{{ dsc.exposedCA.type == 'none' }}"
    method: post
    status_code: 204
  with_items:
    - scan
    - provisioning

- name: Create metrics resources
  when: dsc.global.metrics.enabled
  block:
    - name: Get SonarQube pod
      kubernetes.core.k8s_info:
        kind: Pod
        namespace: "{{ dsc.sonarqube.namespace }}"
        label_selectors:
          - app=sonarqube
          - release=sonarqube
      register: sonarqube_pod

    - name: Set metrics ports names facts
      loop: "{{ metrics_ports_names_facts }}"
      ansible.builtin.set_fact:
        "{{ item.fact_name }}": "{{ sonarqube_pod.resources
          | map(attribute='spec.containers') | first
          | selectattr('name', 'contains', 'sonarqube')
          | map(attribute='ports') | first
          | selectattr('containerPort', 'equalto', item.port)
          | map(attribute='name') | first }}"

    - name: Set metrics paths facts
      loop: "{{ metrics_paths_facts }}"
      ansible.builtin.set_fact:
        "{{ item.fact_name }}": "{{ item.path }}"

    - name: Create PodMonitor
      kubernetes.core.k8s:
        template: podmonitor.yml.j2
