- name: Get pending plugins
  ansible.builtin.uri:
    url: "https://{{ sonar_domain }}/api/plugins/pending"
    return_content: true
    user: "{{ token_pass }}"
    force_basic_auth: true
  register: plugins_pending

- name: Restart to finish installation
  when: plugins_pending.json.installing | plugins_includes('authoidc') | bool
  ansible.builtin.include_tasks:
    file: restart.yaml

- name: Get installed plugins
  ansible.builtin.uri:
    url: "https://{{ sonar_domain }}/api/plugins/installed"
    return_content: true
    user: "{{ token_pass }}"
    force_basic_auth: true
  register: plugins_installed

- name: Install missing authoidc plugin
  when: not (plugins_installed.json.plugins | plugins_includes('authoidc'))
  block:
    - name: Install authoidc plugin
      ansible.builtin.uri:
        url: "https://{{ sonar_domain }}/api/plugins/install?key=authoidc"
        return_content: true
        user: "{{ token_pass }}"
        force_basic_auth: true
        method: POST
        status_code: 204

    - name: Restart to finish installation
      ansible.builtin.include_tasks:
        file: restart.yaml
