- name: Get system status
  ansible.builtin.uri:
    url: "https://{{ sonar_domain }}/api/system/status"
    return_content: true
    validate_certs: "{{ dsc.exposedCA.type == 'none' }}"
    status_code: [503, 200]
    user: "{{ token_pass }}"
    force_basic_auth: true
  register: status
  until: status.json is defined and status.json.status == "UP"
  retries: 10
  delay: 10
