---
- name: Create dso-console namespace
  kubernetes.core.k8s:
    name: "{{ dsc.console.namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: Create dso configmap
  kubernetes.core.k8s:
    definition:
      kind: ConfigMap
      metadata:
        name: dso-config
        namespace: "{{ dsc.console.namespace }}"
      data:
        ARGOCD_URL: https://{{ argocd_domain }}/
        GITLAB_URL: https://{{ gitlab_domain }}/
        HARBOR_URL: https://{{ harbor_domain }}/
        KEYCLOAK_URL: https://{{ keycloak_domain }}/
        NEXUS_URL: https://{{ nexus_domain }}/
        SONARQUBE_URL: https://{{ sonar_domain }}/
        VAULT_URL: https://{{ vault_domain }}/
        HARBOR_ADMIN: admin
        # HARBOR_ADMIN_PASSWORD: roles/harbor/tasks/main.yaml
        KEYCLOAK_ADMIN: admin
        # KEYCLOAK_ADMIN_PASSWORD: roles/keycloak/tasks/main.yaml
        # GITLAB_TOKEN: roles/gitlab/tasks/main.yaml
        NEXUS_ADMIN: admin
        # NEXUS_ADMIN_PASSWORD: roles/nexus/tasks/main.yaml
        # SONAR_API_TOKEN: roles/sonarqube/tasks/main.yaml
        # VAULT_TOKEN: roles/vault/tasks/main.yaml
        ARGO_NAMESPACE: "{{ dsc.argocd.namespace }}"
        PROJECTS_ROOT_DIR: "{{ dsc.global.projectsRootDir | join('/') }}"
