- hosts: localhost
  pre_tasks:
    - name: Load vars
      ansible.builtin.include_vars:
        file: vars.yaml
      tags:
        - always
  roles:
    - name: ansible-inventory
      tags:
        - always
    - name: cert-manager
      tags:
        - cert-manager
    - name: vault
      tags:
        - vault
    - name: confSyncer
      tags:
        - confSyncer
        - kubed
    - name: sonarqube
      tags:
        - sonarqube
    - name: keycloak
      tags:
        - keycloak
    - name: argocd
      tags:
        - gitops
        - argocd
    - name: harbor
      tags:
        - harbor
        - registry
    - name: nexus
      tags:
        - nexus
    - name: gitlab
      tags:
        - gitlab
    - name: gitlab-runner
      tags:
        - gitlab-runner
    - name: console-dso
      tags:
        - console
        - console-dso
