- hosts: localhost
  gather_facts: false

  roles:
    - name: socle-config
      tags:
        - always

    - name: cluster-ca
      when: CA_ENABLED
      tags:
        - always

    - name: console-dso-config
      tags:
        - always

    - name: cert-manager
      tags:
        - cert-manager
        - always

    - name: confSyncer
      tags:
        - confSyncer
        - kubed

    - name: keycloak
      tags:
        - keycloak

    - name: nexus
      tags:
        - nexus

    - name: sonarqube
      tags:
        - sonarqube

    - name: gitlab
      tags:
        - gitlab

    - name: gitlab-runner
      tags:
        - gitlab-runner

    - name: vault
      tags:
        - vault

    - name: sops
      tags:
        - sops

    - name: argocd
      tags:
        - gitops
        - argocd

    - name: harbor
      tags:
        - harbor
        - registry

    - name: console-dso
      tags:
        - console
        - console-dso

  post_tasks:
    - name: Remove local vars
      ansible.builtin.file:
        state: absent
        path: vars.yaml
      tags:
        - always
