- hosts: localhost
  pre_tasks:
    - name: Load vars
      ansible.builtin.include_vars:
        file: vars.yaml
      tags:
        - always
  roles:
    - name: ansible-inventory

    - name: cluster-ca
      tags:
        - always

      tags:
        - always

    - name: cert-manager
      tags:
        - cert-manager

    - name: confSyncer
      tags:
        - confSyncer
        - kubed

    - name: keycloak
      tags:
        - keycloak

    - name: nexus
      tags:
        - nexus

    - name: sonarqube
      tags:
        - sonarqube

    - name: gitlab
      tags:
        - gitlab

    - name: gitlab-runner
      tags:
        - gitlab-runner

    - name: vault
      tags:
        - vault

    - name: argocd
      tags:
        - gitops
        - argocd

    - name: harbor
      tags:
        - harbor
        - registry

    - name: console-dso
      tags:
        - console
        - console-dso
