---
# https://kubernetes.io/docs/concepts/configuration/configmap/
kind: DsoSocleConfig
apiVersion: cloud-pi-native.fr/v1alpha
metadata:
  name: conf-dso
spec:
  general:
    registry: ""
  argocd:
    namespace: dso-argocd
    subDomain: argocd
  cloudnativepg:
    namespace: dso-cloudnativepg
  console:
    namespace: dso-console
    subDomain: console
  gitlabOperator:
    namespace: dso-gitlab-operator
  gitlab:
    namespace: dso-gitlab
    subDomain: gitlab
    insecureCI: false
  grafana:
    namespace: dso-grafana
    subDomain: grafana
    grafanaPvcSize: 5Gi
  grafanaOperator:
    namespace: dso-grafana-operator
  harbor:
    namespace: dso-harbor
    subDomain: harbor
  keycloak:
    namespace: dso-keycloak
    subDomain: keycloak
    postgresPvcSize: 1Gi
  kyverno:
    namespace: dso-kyverno
  nexus:
    namespace: dso-nexus
    subDomain: nexus
  sonarqube:
    namespace: dso-sonarqube
    subDomain: sonar
    postgresPvcSize: 5Gi
  vault:
    namespace: dso-vault
    subDomain: vault
