---
kind: DsoSocleConfig
apiVersion: cloud-pi-native.fr/v1alpha
metadata:
  name: conf-dso
spec:
  certmanager: {}
  additionalsCA: []
  exposedCA:
    type: none
  argocd:
    admin:
      enabled: false
  cloudnativepg: {}
  console:
    dbPassword: myAwesomePassword
    values: {}
  gitlab: {}
  global:
    environment: production
    projectsRootDir:
      - forge
    rootDomain:
      .example.com
  harbor:
    adminPassword: anotherGreatPassword
    pvcRegistrySize: 20Gi
  ingress:
    tls:
      type: none
  kubed: {}
  keycloak: {}
  nexus:
    storageSize: 25Gi
  proxy:
    enabled: false
  sonarqube: {}
  sops: {}
  vault: {}
