---
# https://kubernetes.io/docs/concepts/configuration/configmap/
kind: DsoSocleConfig
apiVersion: cloud-pi-native.fr/v1alpha
metadata:
  name: conf-dso
spec:
  additionalsCA: []
  exposedCA:
    type: none
  argocd:
    chartVersion: ""
  certmanager:
    version: ""
  cloudnativepg:
    chartVersion: ""
    namespace: ""
  console:
    dbPassword: myAwesomePassword
  gitlab:
    chartVersion: ""
  global:
    environment: ""
    projectsRootDir: []
    rootDomain: ""
  harbor:
    adminPassword: anotherGreatPassword
    chartVersion: ""
  ingress: {}
  keycloak:
    chartVersion: ""
  kubed:
    chartVersion: ""
  nexus:
    storageSize: ""
    imageTag: ""
  proxy:
    enabled: false
  sonarqube:
    chartVersion: ""
  sops:
    chartVersion: ""
  vault:
    chartVersion: ""
