---
# https://kubernetes.io/docs/concepts/configuration/configmap/
kind: DsoSocleConfig
apiVersion: cloud-pi-native.fr/v1alpha
metadata:
  name: conf-dso
spec:
  additionalsCA: []
  exposedCA:
    type: none
  argocd:
    chartVersion: ""
  certmanager:
    version: v1.11.0
  cloudnativepg:
    chartVersion: ""
  console:
    dbPassword: myAwesomePassword
  gitlab:
    chartVersion: "6.11.10"
  global:
    projectsRootDir:
      - forge
    rootDomain:
      .example.com
  harbor:
    adminPassword: anotherGreatPassword
    chartVersion: ""
  ingress: {}
  keycloak: {}
  kubed:
    chartVersion: ""
  nexus:
    storageSize: 25Gi
    imageTag: ""
  proxy:
    enabled: false
  sonarqube:
    imageTag: ""
  sops:
    chartVersion: ""
  vault:
    chartVersion: ""
