---
- name: Create GitLab Operator namespace
  kubernetes.core.k8s:
    name: "{{ dsc.gitlabOperator.namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: Add GitLab Operator helm repo
  kubernetes.core.helm_repository:
    name: gitlab-operator
    repo_url: https://gitlab.com/api/v4/projects/18899486/packages/helm/stable

- name: Set GitLab Operator helm values
  ansible.builtin.set_fact:
    operator_values: "{{ lookup('template', 'values.yaml.j2') | from_yaml }}"

- name: Deploy GitLab Operator helm
  kubernetes.core.helm:
    name: gitlab-operator
    chart_ref: gitlab-operator/gitlab-operator
    chart_version: "{{ dsc.gitlabOperator.chartVersion }}"
    release_namespace: "{{ dsc.gitlabOperator.namespace }}"
    values: "{{ operator_values }}"

- name: Wait gitlab-webhook-service endpoint
  kubernetes.core.k8s_info:
    kind: Endpoints
    namespace: "{{ dsc.gitlabOperator.namespace }}"
    name: gitlab-webhook-service
  register: endpoint
  until: endpoint.resources[0].subsets[0].addresses[0] is defined
  retries: 15
  delay: 5
