- name: Create or update DsoSocleConfig CRD
  kubernetes.core.k8s:
    definition: "{{ lookup('ansible.builtin.file', 'crd-conf-dso.yaml') | from_yaml }}"

- name: Get socle config from dsc
  kubernetes.core.k8s_info:
    kind: dsc
    name: conf-dso
    api_version: cloud-pi-native.fr/v1alpha
  register: socle_config

- name: Initialize config and exit
  when: socle_config.resources | length == 0
  block:
    - name: Create socle config example
      kubernetes.core.k8s:
        definition: "{{ lookup('ansible.builtin.file', 'cr-conf-dso-default.yaml') | from_yaml }}"

    - name: Disclaimer
      ansible.builtin.debug:
        msg:
          - "Il semblerait que vous n'ayez jamais installé le socle sur ce cluster."
          - "Veuillez modifier la resource de type dsc nommée conf-dso et de scope cluster"
          - "via la commande suivante :"
          - ""
          - "kubectl edit dsc conf-dso"
          - ""
          - "Puis relancer l'installation."
          - ""
          - "Alternativement, vous pouvez aussi déclarer la resource conf-dso dans un fichier YAML"
          - "nommé par exemple 'ma-conf-dso.yaml' et la créer via la commande suivante :"
          - ""
          - "kubectl apply -f ma-conf-dso.yaml"
          - ""
          - "Puis relancer l'installation."

    - name: Exit playbook
      ansible.builtin.meta: end_play

- name: Set DSC fact
  ansible.builtin.set_fact:
    dsc: "{{ socle_config.resources[0].spec }}"

- name: Set root_domain fact
  ansible.builtin.set_fact:
    root_domain: "{{ dsc.global.rootDomain }}"

- name: Set tools domains facts
  ansible.builtin.set_fact:
    argocd_domain: "{{ dsc.argocd.subDomain }}{{ root_domain }}"
    console_domain: "{{ dsc.console.subDomain }}{{ root_domain }}"
    gitlab_domain: "{{ dsc.gitlab.subDomain }}{{ root_domain }}"
    harbor_domain: "{{ dsc.harbor.subDomain }}{{ root_domain }}"
    keycloak_domain: "{{ dsc.keycloak.subDomain }}{{ root_domain }}"
    nexus_domain: "{{ dsc.nexus.subDomain }}{{ root_domain }}"
    sonar_domain: "{{ dsc.sonarqube.subDomain }}{{ root_domain }}"
    vault_domain: "{{ dsc.vault.subDomain }}{{ root_domain }}"

# - name: Debug domains facts
#   ansible.builtin.debug:
#     msg:
#       - "argocd_domain: {{ argocd_domain }}"
#       - "gitlab_domain: {{ gitlab_domain }}"
#       - "harbor_domain: {{ harbor_domain }}"
#       - "keycloak_domain: {{ keycloak_domain }}"
#       - "nexus_domain: {{ nexus_domain }}"
#       - "sonar_domain: {{ sonar_domain }}"
#       - "vault_domain: {{ vault_domain }}"
# 
# - name: End playbook
#   ansible.builtin.meta: end_play
