- name: no exposed_ca
  when: exposed_ca.type == 'none'
  set_fact:
    exposed_ca_pem: ""

- name: exposed_ca (configmap)
  when: exposed_ca.type == 'configmap'
  block:
    - name: get configMap
      kubernetes.core.k8s_info:
        name: "{{ exposed_ca.configmap.name }}"
        namespace: "{{ exposed_ca.configmap.namespace }}"
        kind: ConfigMap
      register: exposed_ca_resource

    - name: extract key
      set_fact:
        exposed_ca_pem: "{{ exposed_ca_resource.resources[0].data[exposed_ca.configmap.key] }}"

- name: exposed_ca (secret)
  when: exposed_ca.type == 'secret'
  block:
    - name: get secret
      kubernetes.core.k8s_info:
        name: "{{ exposed_ca.configmap.name }}"
        namespace: "{{ exposed_ca.configmap.namespace }}"
        kind: Secret
      register: exposed_ca_resource

    - name: extract key
      set_fact:
        exposed_ca_pem: "{{ exposed_ca_resource.resources[0].data[exposed_ca.configmap.key] | b64decode }}"

- name: exposed_ca (certmanager)
  when: exposed_ca.type == 'certmanager'
  block:
    - name: get certmanager secret
      kubernetes.core.k8s_info:
        name: "{{ ingress.tls.ca.secretName }}"
        namespace: "cert-manager"
        kind: Secret
      register: exposed_ca_resource

    - name: extract key
      set_fact:
        exposed_ca_pem: "{{ exposed_ca_resource.resources[0].data['tls.crt'] | b64decode }}"

- name: exposed_ca (url)
  when: exposed_ca.type == 'url'
  block:
    - name: get url
      ansible.builtin.shell:
        cmd: "curl {{ exposed_ca.url }} -s | openssl x509"
      changed_when: false
      register: exposed_ca_resource
      tags: ['skip_ansible_lint']

    - name: extract key
      set_fact:
        exposed_ca_pem: "{{ exposed_ca_resource.stdout }}"
