- name: Get CA cert
  kubernetes.core.k8s_info:
    namespace: "{{ CA_NAMESPACE }}"
    kind: "{{ CA_KIND }}"
    name: "{{ CA_NAME }}"
  tags:
    - always
  when: CA_ENABLED
  register: ca_cert

- name: Set ca fact (cm)
  set_fact:
    ca_pem: "{{ ca_cert.resources[0].data[CA_KEY] }}"
  when: CA_ENABLED
  tags:
    - always

- name: Set ca fact (secret)
  set_fact:
    ca_pem: "{{ ca_cert.resources[0].data[CA_KEY] | b64decode }}"
  when: CA_ENABLED and CA_KIND == 'Secret'
  tags:
    - always
