- name: Apply project
  kubernetes.core.k8s:
    template: project.j2

- name: get console client secret
  kubernetes.core.k8s_info:
    kind: Secret
    namespace: "{{ KEYCLOAK_NAMESPACE }}"
    name: keycloak-client-secret-console-frontend-client
  register: console_frontend_secret
  failed_when: console_frontend_secret.resources | length == 0

- name: get console client secret
  kubernetes.core.k8s_info:
    kind: Secret
    namespace: "{{ KEYCLOAK_NAMESPACE }}"
    name: keycloak-client-secret-console-backend-client
  register: console_backend_secret
  failed_when: console_backend_secret.resources | length == 0

- name: get old app.yaml
  kubernetes.core.k8s_info:
    kind: Application
    namespace: argo-system
    name: console-pi-native
  register: console_app

- name: generate new values (first deployment)
  set_fact:
    session_secret: "{{ lookup('password', '/dev/null length=32 chars=ascii_letters') }}"
  when: console_app.resources | length == 0

- name: Apply app
  kubernetes.core.k8s:
    template: app.yaml.j2
