---
- name: Create console Namespace
  kubernetes.core.k8s:
    definition:
      kind: Namespace
      metadata:
        name: "{{ dsc.console.namespace }}"

- name: Apply project
  kubernetes.core.k8s:
    template: project.j2

- name: Create PostgreSQL cluster and console database
  kubernetes.core.k8s:
    template: pg-cluster-console.yaml.j2

- name: Wait pg-cluster-console-rw endpoint
  kubernetes.core.k8s_info:
    kind: Endpoints
    namespace: "{{ dsc.console.namespace }}"
    name: pg-cluster-console-rw
  register: endpoint
  until: endpoint.resources[0].subsets[0].addresses[0] is defined
  retries: 30
  delay: 5

- name: Wait job.batch/pg-cluster-console-1-initdb to be terminated
  kubernetes.core.k8s_info:
    kind: Job
    api_version: batch/v1
    namespace: "{{ dsc.console.namespace }}"
    name: pg-cluster-console-1-initdb
  register: job1
  until: job1.resources | length == 0
  retries: 30
  delay: 5

- name: Get console frontend client secret
  kubernetes.core.k8s_info:
    kind: Secret
    namespace: "{{ dsc.keycloak.namespace }}"
    name: keycloak-client-secret-console-frontend
  register: console_frontend_secret
  failed_when: console_frontend_secret.resources | length == 0

- name: Get console backend client secret
  kubernetes.core.k8s_info:
    kind: Secret
    namespace: "{{ dsc.keycloak.namespace }}"
    name: keycloak-client-secret-console-backend
  register: console_backend_secret
  failed_when: console_backend_secret.resources | length == 0

- name: Get old app.yaml
  kubernetes.core.k8s_info:
    kind: Application
    namespace: "{{ dsc.argocd.namespace }}"
    name: console-pi-native
  register: console_app

- name: Generate new values (first deployment)
  ansible.builtin.set_fact:
    session_secret: "{{ lookup('password', '/dev/null length=32 chars=ascii_letters') }}"
  when: console_app.resources | length == 0

- name: Set bundle-ca cm
  kubernetes.core.k8s:
    name: bundle
    namespace: "{{ dsc.console.namespace }}"
    kind: ConfigMap
    api_version: v1
    definition:
      data:
        ca.pem: |
          {{ exposed_ca_pem }}
  when: dsc.exposedCA.type != 'none'

- name: Set path fact
  ansible.builtin.set_fact:
    path: "{{ role_path + '/templates/values' }}"

- name: Get pg-cluster-console-app secret
  kubernetes.core.k8s_info:
    namespace: "{{ dsc.console.namespace }}"
    kind: Secret
    name: pg-cluster-console-app
  register: pg_db_secret

- name: Compute Console Helm values
  ansible.builtin.include_role:
    name: combine
  vars:
    combine_path: "{{ path }}"
    combine_user_values: "{{ dsc.console['values'] }}"
    combine_dest_var: "console_values"

- name: Apply app
  kubernetes.core.k8s:
    template: app.yaml.j2
