- name: Create SOPS namespace
  kubernetes.core.k8s:
    state: present
    kind: namespace
    name: "{{ dsc.sops.namespace }}"
    api_version: v1

- name: Add helm repo
  kubernetes.core.helm_repository:
    name: sops
    repo_url: https://isindir.github.io/sops-secrets-operator

- name: Check if age secret already exists
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Secret
    name: sops-age-key-file
    namespace: "{{ dsc.sops.namespace }}"
  register: age_secret

- name: Generate age keys
  ansible.builtin.command:
    cmd: age-keygen
  register: age_keys
  when: age_secret.resources | length == 0
  changed_when: false

- name: Create secret sops-age-key-file
  kubernetes.core.k8s:
    definition:
      data:
        keys: "{{ age_keys.stdout | b64encode }}"
      kind: Secret
      metadata:
        name: sops-age-key-file
        namespace: "{{ dsc.sops.namespace }}"
      type: Opaque
  when: age_secret.resources | length == 0

- name: Set extra env vars
  ansible.builtin.set_fact:
    sops_values: "{{ lookup('template', 'values.yaml.j2') | from_yaml }}"

- name: Merge with SOPS user values
  ansible.builtin.set_fact:
    sops_values: "{{ sops_values | combine(dsc.sops['values'], recursive=True) }}"

- name: Deploy helm
  kubernetes.core.helm:
    name: "{{ dsc_name }}-sops"
    chart_ref: sops/sops-secrets-operator
    chart_version: "{{ dsc.sops.chartVersion }}"
    release_namespace: "{{ dsc.sops.namespace }}"
    create_namespace: true
    values: "{{ sops_values }}"

- name: Get age secret
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Secret
    name: sops-age-key-file
    namespace: "{{ dsc.sops.namespace }}"
  register: age_secret

- name: Retrieve age public key
  ansible.builtin.set_fact:
    age_pubkey: "{{ age_secret.resources[0].data['keys'] | b64decode | regex_search('public key: (.+)', '\\1', multiline=True) | first }}"

- name: Display age public key message
  ansible.builtin.debug:
    msg:
      - "Clé publique age : {{ age_pubkey }} "
      - "À conserver et fournir à vos utilisateurs."
      - "Elle leur servira à chiffrer leurs secrets."
