- name: Check cert-manager deployment
  kubernetes.core.k8s_info:
    kind: Deployment
    namespace: cert-manager
    name: cert-manager-webhook
  register: cert_manager_webhook

- name: Download cert-manager
  ansible.builtin.uri:
    url: "https://github.com/cert-manager/cert-manager/releases/download/{{ CERTMANAGER_VERSION }}/cert-manager.yaml"
    return_content: true
  register: cert_manifest

- name: Edit manifest
  set_fact:
    manifest: "{{ cert_manifest.content | from_yaml_all | custom_cert_manager(envs) }}"
  vars:
    envs:
      - name: http_proxy
        value: "{{ HTTP_PROXY }}"
      - name: https_proxy
        value: "{{ HTTPS_PROXY }}"
      - name: no_proxy
        value: "{{ NO_PROXY }}"
  when: USE_PROXY

- name: Apply cert-manager
  kubernetes.core.k8s:
    state: present
    definition: "{{ manifest | default(cert_manifest.content | from_yaml_all) }}"

- name: Create ClusterIssuer
  kubernetes.core.k8s:
    state: present
    template: "{{ item }}"
  with_items:
    - cluster-issuer.j2
