---
- name: Get credentials
  hosts: localhost
  gather_facts: false
  tasks:

    - name: Get socle config
      kubernetes.core.k8s_info:
        kind: ConfigMap
        namespace: cluster-infra
        name: socle-config
      register: socle_config

    - name: Save vars locally and temporally
      ansible.builtin.copy:
        dest: vars.yaml
        content: "{{ socle_config.resources[0].data.vars | from_yaml | to_nice_yaml }}"
        mode: "0400"

    - name: Load vars
      ansible.builtin.include_vars:
        file: vars.yaml
      tags:
        - always

    - name: Get Keycloak ingress
      kubernetes.core.k8s_info:
        namespace: "{{ KEYCLOAK_NAMESPACE }}"
        kind: Ingress
        api_version: networking.k8s.io/v1
        name: keycloak-alternative
      register: keycloak_ingress

    - name: Get Keycloak credentials
      kubernetes.core.k8s_info:
        namespace: "{{ KEYCLOAK_NAMESPACE }}"
        kind: Secret
        name: credential-dso-keycloak
      register: keycloak_creds

    - name: Set Keycloak admin facts
      ansible.builtin.set_fact:
        keycloak_url: "https://{{ keycloak_ingress.resources[0].spec.rules[0].host }}"
        keycloak_admin: "{{ keycloak_creds.resources[0].data.ADMIN_USERNAME | b64decode }}"
        keycloak_admin_password: "{{ keycloak_creds.resources[0].data.ADMIN_PASSWORD | b64decode }}"

    - name: Display Keycloak credentials
      ansible.builtin.debug:
        msg:
          - "URL : {{ keycloak_url }} "
          - "Admin username : {{ keycloak_admin }} "
          - "Admin password : {{ keycloak_admin_password }} "

    - name: Get dso-config configmap
      kubernetes.core.k8s_info:
        namespace: "{{ CONSOLE_NAMESPACE }}"
        kind: Secret
        name: dso-config
      register: dso_configmap

    - name: Get Vault unseal keys and root token
      kubernetes.core.k8s_info:
        namespace: "{{ VAULT_NAMESPACE }}"
        kind: Secret
        name: vault-keys
      register: vault_keys

    - name: Display Vault URL, unseal keys and root token
      ansible.builtin.debug:
        msg:
          - "URL: {{ dso_configmap }}"
          - "key1: {{ vault_keys.resources[0].data.key1 | b64decode }} "
          - "key2: {{ vault_keys.resources[0].data.key2 | b64decode }} "
          - "key3: {{ vault_keys.resources[0].data.key3 | b64decode }} "
          - "root_token: {{ vault_keys.resources[0].data.root_token | b64decode }} "
