---
- name: Get credentials
  hosts: localhost
  gather_facts: false
  tasks:

    - name: Get socle config
      kubernetes.core.k8s_info:
        kind: ConfigMap
        namespace: cluster-infra
        name: socle-config
      register: socle_config
      tags:
        - always

    - name: Save vars locally and temporally
      ansible.builtin.copy:
        dest: vars.yaml
        content: "{{ socle_config.resources[0].data.vars | from_yaml | to_nice_yaml }}"
        mode: "0400"
      tags:
        - always

    - name: Load vars
      ansible.builtin.include_vars:
        file: vars.yaml
      tags:
        - always

    - name: Get dso-config configmap
      kubernetes.core.k8s_info:
        namespace: "{{ CONSOLE_NAMESPACE }}"
        kind: ConfigMap
        name: dso-config
      register: dso_configmap
      tags:
        - always

    - name: Get Keycloak DSO user credentials
      kubernetes.core.k8s_info:
        namespace: "{{ KEYCLOAK_NAMESPACE }}"
        kind: Secret
        name: credential-dso-adminexample.com-keycloak-system
      register: keycloak_user_creds
      tags:
        - always

    - name: Set Keycloak user facts
      ansible.builtin.set_fact:
        keycloak_user: "{{ keycloak_user_creds.resources[0].data.username | b64decode }}"
        keycloak_user_password: "{{ keycloak_user_creds.resources[0].data.password | b64decode }}"
      tags:
        - always

    - name: Get Keycloak ingress
      kubernetes.core.k8s_info:
        namespace: "{{ KEYCLOAK_NAMESPACE }}"
        kind: Ingress
        api_version: networking.k8s.io/v1
        name: keycloak-alternative
      register: keycloak_ingress
      tags:
        - keycloak

    - name: Get Keycloak admin credentials
      kubernetes.core.k8s_info:
        namespace: "{{ KEYCLOAK_NAMESPACE }}"
        kind: Secret
        name: credential-dso-keycloak
      register: keycloak_admin_creds
      tags:
        - keycloak

    - name: Set Keycloak admin facts
      ansible.builtin.set_fact:
        keycloak_url: "https://{{ keycloak_ingress.resources[0].spec.rules[0].host }}"
        keycloak_admin: "{{ keycloak_admin_creds.resources[0].data.ADMIN_USERNAME | b64decode }}"
        keycloak_admin_password: "{{ keycloak_admin_creds.resources[0].data.ADMIN_PASSWORD | b64decode }}"
      tags:
        - keycloak

    - name: Display Keycloak credentials
      ansible.builtin.debug:
        msg:
          - "URL : {{ keycloak_url }} "
          - "Admin username : {{ keycloak_admin }} "
          - "Admin password : {{ keycloak_admin_password }} "
      tags:
        - keycloak

    - name: Display Nexus credentials
      ansible.builtin.debug:
        msg:
          - "URL: {{ dso_configmap.resources[0].data.NEXUS_URL }} "
          - "Admin username: {{ dso_configmap.resources[0].data.NEXUS_ADMIN }} "
          - "Admin password: {{ dso_configmap.resources[0].data.NEXUS_ADMIN_PASSWORD }} "
      tags:
        - nexus

    - name: Display Sonarqube URL and API token
      ansible.builtin.debug:
        msg:
          - "URL: {{ dso_configmap.resources[0].data.SONARQUBE_URL }} "
          - "API token: {{ dso_configmap.resources[0].data.SONAR_API_TOKEN }} "
      tags:
        - sonar
        - sonarqube

    - name: Display Gitlab URL, credentials and API token
      ansible.builtin.debug:
        msg:
          - "URL: {{ dso_configmap.resources[0].data.GITLAB_URL }} "
          - "Admin username: {{ keycloak_user }} "
          - "Admin password: {{ keycloak_user_password }}"
          - "API token: {{ dso_configmap.resources[0].data.GITLAB_TOKEN }} "
      tags:
        - gitlab

    - name: Get Vault unseal keys and root token
      kubernetes.core.k8s_info:
        namespace: "{{ VAULT_NAMESPACE }}"
        kind: Secret
        name: vault-keys
      register: vault_keys
      tags:
        - vault

    - name: Display Vault URL, root token and unseal keys
      ansible.builtin.debug:
        msg:
          - "URL: {{ dso_configmap.resources[0].data.VAULT_URL }} "
          - "root_token: {{ vault_keys.resources[0].data.root_token | b64decode }} "
          - "key1: {{ vault_keys.resources[0].data.key1 | b64decode }} "
          - "key2: {{ vault_keys.resources[0].data.key2 | b64decode }} "
          - "key3: {{ vault_keys.resources[0].data.key3 | b64decode }} "
      tags:
        - vault
