---
- name: Validate dsc.global.registry is not empty
  assert:
    that:
      - dsc.global.registry != ""
    fail_msg: "'dsc.global.registry' must not be empty" 

- name: Validate dsc.sonarqube.pluginDownloadUrl is not empty
  assert:
    that:
      - dsc.sonarqube.pluginDownloadUrl != ""
    fail_msg: "'dsc.sonarqube.pluginDownloadUrl' must not be empty"

- name: Validate dsc.sonarqube.PrometheusJavaagentVersion is not empty
  assert:
    that:
      - dsc.sonarqube.PrometheusJavaagentVersion != ""
    fail_msg: "'dsc.sonarqube.PrometheusJavaagentVersion' must not be empty"

- name: Validate dsc.gitlabCatalog.catalogRepoUrl is different than default
  assert:
    that:
      - dsc.gitlabCatalog.catalogRepoUrl != "https://github.com/cloud-pi-native/gitlab-ci-catalog.git"
    fail_msg: "'dsc.gitlabCatalog.catalogRepoUrl' is same as 'https://github.com/cloud-pi-native/gitlab-ci-catalog.git'"

- name: Validate dsc.gitlabCatalog.catalogBranchesApi is different than default
  assert:
    that:
      - dsc.gitlabCatalog.catalogBranchesApi != "https://api.github.com/repos/cloud-pi-native/gitlab-ci-catalog/branches"  
    fail_msg: "'dsc.gitlabCatalog.catalogBranchesApi' is same as 'https://api.github.com/repos/cloud-pi-native/gitlab-ci-catalog/branches'" 

- name: Validate dsc.gitlabCatalog.catalogTagsApi is different than default
  assert:
    that:
      - dsc.gitlabCatalog.catalogTagsApi != "https://api.github.com/repos/cloud-pi-native/gitlab-ci-catalog/tags"  
    fail_msg: "'dsc.gitlabCatalog.catalogTagsApi' is same as 'https://api.github.com/repos/cloud-pi-native/gitlab-ci-catalog/tags'" 

- name: Validate dsc.console.consoleRepoUrl is different than default
  assert:
    that:
      - dsc.console.consoleRepoUrl != "https://github.com/cloud-pi-native/console.git"
    fail_msg: "'dsc.console.consoleRepoUrl' is same as 'https://github.com/cloud-pi-native/console.git'"

- name: Validate dsc.argocd.privateGitlabDomain is not empty
  assert:
    that:
      - dsc.argocd.privateGitlabDomain != ""
    fail_msg: "'dsc.argocd.privateGitlabDomain' is empty" 
